## Dubbo 服务提供者配置
spring.dubbo:
  application.name: PrepareLessonProvider
  registry.address: zookeeper://127.0.0.1:2181
  protocol.name: dubbo
  protocol.port: 20880
  scan: com.zqy.stage.preparelesson.service
server:
  port: 8082
