## Dubbo 服务提供者配置
spring.dubbo:
  application.name: MemberProvider
  registry.address: zookeeper://127.0.0.1:2181
  protocol.name: dubbo
  protocol.port: 20880
  scan: com.zqy.stage.member.service
server:
  port: 8086

##数据源配置
spring:
  datasource:
    url: jdbc:mysql://rm-2ze1emscmwth2ldalo.mysql.rds.aliyuncs.com:3306/crude-trade-member?useUnicode=true&characterEncoding=utf8
    username: b2b_ccav_test
    password: ccav@1152
    driver-class-name: com.mysql.jdbc.Driver

## Mybatis 配置
mybatis:
  type-aliases-package: com.zqy.stage.member.model
  mapper-locations: classpath:mapper/*.xml